/**
 * Screen H2's copy across all 5 supported UI languages.
 *
 * Local to this folder rather than in `src/i18n/uz_latn.ts` / `ru.ts`: those
 * dictionaries are shared by every screen and edited by parallel sessions.
 * The shape gives compile-time parity: each language is typed as `RoleScreenLabels`
 * (matching `typeof uz_latn`), so missing or misspelled keys fail at build time.
 */

import type { UiLanguage } from '../../../i18n/context';
import { pickName } from '../../applicant/format';
import { translateTerm } from '../../../i18n/terms';

const uz_latn = {
  title: 'Rollar va huquqlar',
  subtitle: 'Har bir rol tizimda qaysi amallarni bajara olishini shu yerda belgilanadi',
  listTitle: 'Rollar',
  listHint: 'Huquqlarini koʻrish uchun rolni tanlang',
  matrixTitle: 'Huquqlar matritsasi',
  emptySelection: 'Rol tanlanmagan',
  emptySelectionHint: 'Roʻyxatdan rolni tanlang — uning huquqlari shu yerda ochiladi',
  systemBadge: 'Tizim roli',
  statusActive: 'Faol',
  statusArchived: 'Arxivlangan',
  permissionsSuffix: 'ta huquq',
  holdersSuffix: 'ta foydalanuvchi',
  selectedOf: 'tanlangan',
  save: 'Saqlash',
  saving: 'Saqlanmoqda...',
  saved: 'Huquqlar saqlandi',
  reset: 'Tiklash',
  loading: 'Yuklanmoqda...',
  loadError: 'Rollar roʻyxati yuklanmadi.',
  saveError: 'Huquqlarni saqlab boʻlmadi.',
  systemNote: 'Tizim rolining kodi va nomi bu yerda oʻzgartirilmaydi — faqat huquqlar tahrirlanadi.',
  applicantNote:
    'Ariza beruvchi roliga xodim huquqlari berilmaydi — server bunday saqlashni rad etadi (ERR-VAL-001).',
  emptyRoles: 'Rollar topilmadi.',
  emptyPermissions: 'Huquqlar registri boʻsh.',
  groups: {
    applications: 'Arizalar',
    permits: 'Ruxsatnomalar',
    payments: 'Toʻlovlar',
    norms: 'Hisob-kitob va normalar',
    gis: 'Xaritalar va konturlar',
    signatures: 'Elektron imzo',
    notifications: 'Xabarnomalar',
    auth: 'Foydalanuvchilar va rollar',
    admin: 'Maʼmuriyat',
    oversight: 'Nazorat',
    inspections: 'Tekshiruvlar',
    reports: 'Hisobotlar',
    search: 'Qidiruv',
    archive: 'Arxiv',
    users: 'Foydalanuvchilar',
  },
};

export type RoleScreenLabels = typeof uz_latn;

const ru: RoleScreenLabels = {
  title: 'Роли и права',
  subtitle: 'Здесь задаётся, какие действия в системе может выполнять каждая роль',
  listTitle: 'Роли',
  listHint: 'Выберите роль, чтобы увидеть её права',
  matrixTitle: 'Матрица прав',
  emptySelection: 'Роль не выбрана',
  emptySelectionHint: 'Выберите роль в списке — её права откроются здесь',
  systemBadge: 'Системная роль',
  statusActive: 'Активна',
  statusArchived: 'В архиве',
  permissionsSuffix: 'прав',
  holdersSuffix: 'пользователей',
  selectedOf: 'выбрано',
  save: 'Сохранить',
  saving: 'Сохранение...',
  saved: 'Права сохранены',
  reset: 'Сбросить',
  loading: 'Загрузка...',
  loadError: 'Не удалось загрузить список ролей.',
  saveError: 'Не удалось сохранить права.',
  systemNote: 'Код и название системной роли здесь не меняются — редактируются только права.',
  applicantNote:
    'Роли заявителя нельзя выдать права сотрудника — сервер отклонит такое сохранение (ERR-VAL-001).',
  emptyRoles: 'Роли не найдены.',
  emptyPermissions: 'Реестр прав пуст.',
  groups: {
    applications: 'Заявки',
    permits: 'Разрешения',
    payments: 'Платежи',
    norms: 'Расчёт и нормативы',
    gis: 'Карты и контуры',
    signatures: 'Электронная подпись',
    notifications: 'Уведомления',
    auth: 'Пользователи и роли',
    admin: 'Администрирование',
    oversight: 'Надзор',
    inspections: 'Проверки',
    reports: 'Отчёты',
    search: 'Поиск',
    archive: 'Архив',
    users: 'Пользователи',
  },
};

const uz_cyrl: RoleScreenLabels = {
  title: 'Роллар ва ҳуқуқлар',
  subtitle: 'Ҳар бир рол тизимда қайси амалларни бажара олишини шу ерда белгиланади',
  listTitle: 'Роллар',
  listHint: 'Ҳуқуқларини кўриш учун ролни танланг',
  matrixTitle: 'Ҳуқуқлар матрицаси',
  emptySelection: 'Рол танланмаган',
  emptySelectionHint: 'Рўйхатдан ролни танланг — унинг ҳуқуқлари шу ерда очилади',
  systemBadge: 'Тизим роли',
  statusActive: 'Фаол',
  statusArchived: 'Архивланган',
  permissionsSuffix: 'та ҳуқуқ',
  holdersSuffix: 'та фойдаланувчи',
  selectedOf: 'танланган',
  save: 'Сақлаш',
  saving: 'Сақланмоқда...',
  saved: 'Ҳуқуқлар сақланди',
  reset: 'Тиклаш',
  loading: 'Юкланмоқда...',
  loadError: 'Роллар рўйхати юкланмади.',
  saveError: 'Ҳуқуқларни сақлаб бўлмади.',
  systemNote: 'Тизим ролининг коди ва номи бу ерда ўзгартирилмайди — фақат ҳуқуқлар таҳрирланади.',
  applicantNote:
    'Ариза берувчи ролига ходим ҳуқуқлари берилмайди — сервер бундай сақлашни рад этади (ERR-VAL-001).',
  emptyRoles: 'Роллар топилмади.',
  emptyPermissions: 'Ҳуқуқлар регистри бўш.',
  groups: {
    applications: 'Аризалар',
    permits: 'Рухсатномалар',
    payments: 'Тўловлар',
    norms: 'Ҳисоб-китоб ва нормалар',
    gis: 'Хариталар ва контурлар',
    signatures: 'Электрон имзо',
    notifications: 'Хабарномалар',
    auth: 'Фойдаланувчилар ва роллар',
    admin: 'Маъмурият',
    oversight: 'Назорат',
    inspections: 'Текширувлар',
    reports: 'Ҳисоботлар',
    search: 'Қидирув',
    archive: 'Архив',
    users: 'Фойдаланувчилар',
  },
};

const en: RoleScreenLabels = {
  title: 'Roles and permissions',
  subtitle: 'Configure which system actions each role is authorized to perform',
  listTitle: 'Roles',
  listHint: 'Select a role to view its permissions',
  matrixTitle: 'Permissions matrix',
  emptySelection: 'No role selected',
  emptySelectionHint: 'Select a role from the list — its permissions will open here',
  systemBadge: 'System role',
  statusActive: 'Active',
  statusArchived: 'Archived',
  permissionsSuffix: 'permissions',
  holdersSuffix: 'users',
  selectedOf: 'selected',
  save: 'Save',
  saving: 'Saving...',
  saved: 'Permissions saved',
  reset: 'Reset',
  loading: 'Loading...',
  loadError: 'Failed to load roles list.',
  saveError: 'Failed to save permissions.',
  systemNote: 'System role code and name cannot be changed here — only permissions can be edited.',
  applicantNote:
    'Staff permissions cannot be granted to applicant role — server will reject this save (ERR-VAL-001).',
  emptyRoles: 'No roles found.',
  emptyPermissions: 'Permission registry is empty.',
  groups: {
    applications: 'Applications',
    permits: 'Permits',
    payments: 'Payments',
    norms: 'Calculations and norms',
    gis: 'Maps and contours',
    signatures: 'Electronic signature',
    notifications: 'Notifications',
    auth: 'Users and roles',
    admin: 'Administration',
    oversight: 'Oversight',
    inspections: 'Inspections',
    reports: 'Reports',
    search: 'Search',
    archive: 'Archive',
    users: 'Users',
  },
};

const kaa: RoleScreenLabels = {
  title: 'Roller hám huqıqlar',
  subtitle: 'Hár bir rol sistemada qaysı ámellerdi orınlay alıwın usı jerde belgilenedi',
  listTitle: 'Roller',
  listHint: 'Huqıqların kóriw ushın roldi saylań',
  matrixTitle: 'Huqıqlar matricası',
  emptySelection: 'Rol saylanbaǵan',
  emptySelectionHint: 'Dizimnen roldi saylań — onıń huqıqları usı jerde ashıladı',
  systemBadge: 'Sistema roli',
  statusActive: 'Belsendi',
  statusArchived: 'Arxivlengen',
  permissionsSuffix: 'huqıq',
  holdersSuffix: 'paydalanıwshı',
  selectedOf: 'saylanǵan',
  save: 'Saqlaw',
  saving: 'Saqlanbaqta...',
  saved: 'Huqıqlar saqlandı',
  reset: 'Qayta tiklew',
  loading: 'Júklenbekte...',
  loadError: 'Roller dizimi júklenbedi.',
  saveError: 'Huqıqlardı saqlap bolmadı.',
  systemNote: 'Sistema roliniń kodı hám atı bul jerde ózgertilmeydi — tek huqıqlar redaktorlanadı.',
  applicantNote:
    'Arza beriwshi roline xızmetker huqıqları berilmeydi — server bunday saqlawdı biykarlaydı (ERR-VAL-001).',
  emptyRoles: 'Roller tabılmadı.',
  emptyPermissions: 'Huqıqlar dizimi bos.',
  groups: {
    applications: 'Arzalar',
    permits: 'Ruxsatnamalar',
    payments: 'Tólemler',
    norms: 'Esap-kitap hám normalar',
    gis: 'Kartalar hám konturlar',
    signatures: 'Elektron qol qoyıw',
    notifications: 'Xabarnamalar',
    auth: 'Paydalanıwshılar hám roller',
    admin: 'Administraciya',
    oversight: 'Qadaǵalaw',
    inspections: 'Tekseriwler',
    reports: 'Esabatlar',
    search: 'İzlew',
    archive: 'Arxiv',
    users: 'Paydalanıwshılar',
  },
};

export const labels: Record<UiLanguage, RoleScreenLabels> = {
  uz_latn,
  ru,
  uz_cyrl,
  kaa,
  en,
};

export const GROUP_ORDER: readonly string[] = [
  'applications',
  'permits',
  'payments',
  'norms',
  'gis',
  'signatures',
  'notifications',
  'oversight',
  'inspections',
  'reports',
  'search',
  'archive',
  'auth',
  'admin',
];

export function groupTitle(prefix: string, lang: UiLanguage | string): string {
  const map = labels[lang as UiLanguage] ?? labels.uz_latn;
  const known = map.groups as Record<string, string | undefined>;
  return known[prefix] ?? prefix;
}

export function pickRoleName(
  role: { name?: Record<string, unknown> | null; code: string },
  lang: UiLanguage | string,
): string {
  const fromName = pickName(role.name, lang);
  if (fromName && fromName.toLowerCase() !== role.code.toLowerCase()) {
    return fromName;
  }
  const fromCode = translateTerm(role.code, lang);
  return fromCode || role.code;
}

export const PERMISSION_DESCRIPTIONS: Record<UiLanguage, Record<string, string>> = {
  uz_latn: {
    'applications.create': 'Ariza yaratish',
    'applications.view_any': 'Ixtiyoriy arizani koʻrish',
    'applications.review': 'Arizalarni koʻrib chiqish',
    'applications.approve': 'Arizani tasdiqlash',
    'applications.decide': 'Ariza boʻyicha qaror qabul qilish',
    'permits.issue': 'Ruxsatnoma berish',
    'permits.view_any': 'Ixtiyoriy ruxsatnomani koʻrish',
    'permits.manage': 'Ruxsatnomalarni boshqarish',
    'permits.revoke': 'Ruxsatnomani bekor qilish',
    'payments.invoices.view': 'Hisob-fakturalarni koʻrish',
    'payments.view': 'Toʻlovlarni koʻrish',
    'payments.confirm': 'Toʻlovni tasdiqlash',
    'payments.refund': 'Toʻlovni qaytarish',
    'norms.calculate': 'Toʻlovni hisoblash',
    'norms.manage': 'Normalarni boshqarish',
    'norms.tariffs.manage': 'Tariflarni boshqarish',
    'norms.approve': 'Normalarni tasdiqlash',
    'gis.contours.manage': 'Konturlarni boshqarish va tahrirlash',
    'gis.contours.approve': 'Konturlarni tasdiqlash',
    'gis.layers.manage': 'Qatlamlarni boshqarish',
    'signatures.sign': 'Elektron raqamli imzo qoʻyish',
    'signatures.view_any': 'Imzolarni koʻrish',
    'notifications.send': 'Xabarnoma yuborish',
    'notifications.view': 'Xabarnomalarni koʻrish',
    'auth.users.manage': 'Foydalanuvchilarni boshqarish',
    'auth.roles.manage': 'Rollar va huquqlarni boshqarish',
    'admin.settings.manage': 'Tizim parametrlarini boshqarish',
    'admin.organizations.manage': 'Tashkilotlarni boshqarish',
    'admin.users.manage': 'Foydalanuvchilarni boshqarish',
    'oversight.view': 'Nazorat daftarini koʻrish',
    'inspections.acts.write': 'Tekshiruv dalolatnomalarini rasmiylashtirish',
    'inspections.tasks.manage': 'Tekshiruv vazifalarini boshqarish',
    'inspections.cases.manage': 'Huquqbuzarlik ishlarini boshqarish',
    'inspections.checklists.manage': 'Nazorat varaqalarini boshqarish',
    'inspections.view_any': 'Ixtiyoriy tekshiruvni koʻrish',
    'reports.view': 'Hisobotlarni koʻrish',
    'reports.manage': 'Hisobotlarni boshqarish',
    'reports.sign': 'Hisobotlarni imzolash',
    'reports.accept': 'Hisobotlarni qabul qilish',
    'search.use': 'Kengaytirilgan qidiruvdan foydalanish',
    'archive.view': 'Arxivni koʻrish',
    'archive.manage': 'Arxivni boshqarish',
  },
  ru: {
    'applications.create': 'Создание заявки',
    'applications.view_any': 'Просмотр любых заявок',
    'applications.review': 'Рассмотрение заявок',
    'applications.approve': 'Утверждение заявки',
    'applications.decide': 'Принятие решения по заявке',
    'permits.issue': 'Выдача разрешения',
    'permits.view_any': 'Просмотр любых разрешений',
    'permits.manage': 'Управление разрешениями',
    'permits.revoke': 'Аннулирование разрешения',
    'payments.invoices.view': 'Просмотр счетов-фактур',
    'payments.view': 'Просмотр платежей',
    'payments.confirm': 'Подтверждение платежа',
    'payments.refund': 'Возврат платежа',
    'norms.calculate': 'Расчёт платежа',
    'norms.manage': 'Управление нормативами',
    'norms.tariffs.manage': 'Управление тарифами',
    'norms.approve': 'Утверждение нормативов',
    'gis.contours.manage': 'Импорт и редактирование контуров',
    'gis.contours.approve': 'Утверждение контуров',
    'gis.layers.manage': 'Управление слоями',
    'signatures.sign': 'Наложение ЭЦП',
    'signatures.view_any': 'Просмотр подписей',
    'notifications.send': 'Отправка уведомлений',
    'notifications.view': 'Просмотр уведомлений',
    'auth.users.manage': 'Создание и редактирование пользователей',
    'auth.roles.manage': 'Управление ролями и правами',
    'admin.settings.manage': 'Управление системными настройками',
    'admin.organizations.manage': 'Управление организациями',
    'admin.users.manage': 'Управление пользователями',
    'oversight.view': 'Просмотр реестра надзора',
    'inspections.acts.write': 'Оформление актов проверок',
    'inspections.tasks.manage': 'Управление заданиями проверок',
    'inspections.cases.manage': 'Управление делами о нарушениях',
    'inspections.checklists.manage': 'Управление чек-листами',
    'inspections.view_any': 'Просмотр любых проверок',
    'reports.view': 'Просмотр отчётов',
    'reports.manage': 'Управление отчётами',
    'reports.sign': 'Подписание отчётов',
    'reports.accept': 'Приёмка отчётов',
    'search.use': 'Использование поиска',
    'archive.view': 'Просмотр архива',
    'archive.manage': 'Управление архивом',
  },
  uz_cyrl: {
    'applications.create': 'Ариза яратиш',
    'applications.view_any': 'Ихтиёрий аризани кўриш',
    'applications.review': 'Аризаларни кўриб чиқиш',
    'applications.approve': 'Аризани тасдиқлаш',
    'applications.decide': 'Ариза бўйича қарор қабул қилиш',
    'permits.issue': 'Рухсатнома бериш',
    'permits.view_any': 'Ихтиёрий рухсатномани кўриш',
    'permits.manage': 'Рухсатномаларни бошқариш',
    'permits.revoke': 'Рухсатномани бекор қилиш',
    'payments.invoices.view': 'Ҳисоб-фактураларни кўриш',
    'payments.view': 'Тўловларни кўриш',
    'payments.confirm': 'Тўловни тасдиқлаш',
    'payments.refund': 'Тўловни қайтариш',
    'norms.calculate': 'Тўловни ҳисоблаш',
    'norms.manage': 'Нормаларни бошқариш',
    'norms.tariffs.manage': 'Тарифларни бошқариш',
    'norms.approve': 'Нормаларни тасдиқлаш',
    'gis.contours.manage': 'Контурларни бошқариш ва таҳрирлаш',
    'gis.contours.approve': 'Контурларни тасдиқлаш',
    'gis.layers.manage': 'Қатламларни бошқариш',
    'signatures.sign': 'Электрон рақамли имзо қўйиш',
    'signatures.view_any': 'Имзоларни кўриш',
    'notifications.send': 'Хабарнома юбориш',
    'notifications.view': 'Хабарномаларни кўриш',
    'auth.users.manage': 'Фойдаланувчиларни бошқариш',
    'auth.roles.manage': 'Роллар ва ҳуқуқларни бошқариш',
    'admin.settings.manage': 'Тизим параметрларини бошқариш',
    'admin.organizations.manage': 'Ташкилотларни бошқариш',
    'admin.users.manage': 'Фойдаланувчиларни бошқариш',
    'oversight.view': 'Назорат дафтарини кўриш',
    'inspections.acts.write': 'Текширув далолатномаларини расмийлаштириш',
    'inspections.tasks.manage': 'Текширув вазифаларини бошқариш',
    'inspections.cases.manage': 'Ҳуқуқбузарлик ишларини бошқариш',
    'inspections.checklists.manage': 'Назорат варақаларини бошқариш',
    'inspections.view_any': 'Ихтиёрий текширувни кўриш',
    'reports.view': 'Ҳисоботларни кўриш',
    'reports.manage': 'Ҳисоботларни бошқариш',
    'reports.sign': 'Ҳисоботларни имзолаш',
    'reports.accept': 'Ҳисоботларни қабул қилиш',
    'search.use': 'Кенгайтирилган қидирувдан фойдаланиш',
    'archive.view': 'Архивни кўриш',
    'archive.manage': 'Архивни бошқариш',
  },
  kaa: {
    'applications.create': 'Arza jaratıw',
    'applications.view_any': 'Qálegen arzanı kóriw',
    'applications.review': 'Arzalardı kórip shıǵıw',
    'applications.approve': 'Arzanı tastıyıqlaw',
    'applications.decide': 'Arza boyınsha qarar qabıllaw',
    'permits.issue': 'Ruxsatnama beriw',
    'permits.view_any': 'Qálegen ruxsatnamanı kóriw',
    'permits.manage': 'Ruxsatnamalardı basqarıw',
    'permits.revoke': 'Ruxsatnamanı biykarlaw',
    'payments.invoices.view': 'Esap-fakturalardı kóriw',
    'payments.view': 'Tólemlerdi kóriw',
    'payments.confirm': 'Tólemdi tastıyıqlaw',
    'payments.refund': 'Tólemdi qaytarıw',
    'norms.calculate': 'Tólemdi esaplaw',
    'norms.manage': 'Normalardı basqarıw',
    'norms.tariffs.manage': 'Tariflerdi basqarıw',
    'norms.approve': 'Normalardı tastıyıqlaw',
    'gis.contours.manage': 'Konturlardı basqarıw hám dúzetiw',
    'gis.contours.approve': 'Konturlardı tastıyıqlaw',
    'gis.layers.manage': 'Qatlamlardı basqarıw',
    'signatures.sign': 'Elektron sanlı qol qoyıw',
    'signatures.view_any': 'Qol qoyıwlardı kóriw',
    'notifications.send': 'Xabarnama jiberiw',
    'notifications.view': 'Xabarnamalardı kóriw',
    'auth.users.manage': 'Paydalanıwshılardı basqarıw',
    'auth.roles.manage': 'Roller hám huqıqlardı basqarıw',
    'admin.settings.manage': 'Sistema parametrlerin basqarıw',
    'admin.organizations.manage': 'Shólkemlerdi basqarıw',
    'admin.users.manage': 'Paydalanıwshılardı basqarıw',
    'oversight.view': 'Qadaǵalaw reestrin kóriw',
    'inspections.acts.write': 'Tekseriw dalalatnamaların rásmiylestiriw',
    'inspections.tasks.manage': 'Tekseriw tapsırmaların basqarıw',
    'inspections.cases.manage': 'Nızambuzarlıq islerin basqarıw',
    'inspections.checklists.manage': 'Qadaǵalaw betlerin basqarıw',
    'inspections.view_any': 'Qálegen tekseriwdi kóriw',
    'reports.view': 'Esabatlardı kóriw',
    'reports.manage': 'Esabatlardı basqarıw',
    'reports.sign': 'Esabatlardı qol qoyıw',
    'reports.accept': 'Esabatlardı qabıllaw',
    'search.use': 'Keńeytilgen izlewden paydalanıw',
    'archive.view': 'Arxivti kóriw',
    'archive.manage': 'Arxivti basqarıw',
  },
  en: {
    'applications.create': 'Create an application',
    'applications.view_any': 'View any application',
    'applications.review': 'Review a submitted application',
    'applications.approve': 'Approve an application',
    'applications.decide': 'Make decision on application',
    'permits.issue': 'Issue a permit',
    'permits.view_any': 'View any permit',
    'permits.manage': 'Manage permits',
    'permits.revoke': 'Revoke a permit',
    'payments.invoices.view': 'View invoices',
    'payments.view': 'View payments',
    'payments.confirm': 'Confirm payment',
    'payments.refund': 'Refund payment',
    'norms.calculate': 'Compute a fee',
    'norms.manage': 'Manage norms',
    'norms.tariffs.manage': 'Manage tariffs',
    'norms.approve': 'Approve norms',
    'gis.contours.manage': 'Import and edit contours',
    'gis.contours.approve': 'Approve contours',
    'gis.layers.manage': 'Manage layers',
    'signatures.sign': 'Attach an ERI signature',
    'signatures.view_any': 'View signatures',
    'notifications.send': 'Send a notification',
    'notifications.view': 'View notifications',
    'auth.users.manage': 'Create and edit users',
    'auth.roles.manage': 'Manage roles and permissions',
    'admin.settings.manage': 'Change runtime system settings',
    'admin.organizations.manage': 'Manage organizations',
    'admin.users.manage': 'Manage users',
    'oversight.view': 'View oversight register',
    'inspections.acts.write': 'Write inspection acts',
    'inspections.tasks.manage': 'Manage inspection tasks',
    'inspections.cases.manage': 'Manage violation cases',
    'inspections.checklists.manage': 'Manage checklists',
    'inspections.view_any': 'View any inspection',
    'reports.view': 'View reports',
    'reports.manage': 'Manage reports',
    'reports.sign': 'Sign reports',
    'reports.accept': 'Accept reports',
    'search.use': 'Use cross-entity search',
    'archive.view': 'View archive',
    'archive.manage': 'Manage archive',
  },
};

export function permissionHint(
  permission: { code: string; description?: string | null },
  lang: UiLanguage,
): string {
  if (lang === 'uz_latn' && permission.description) {
    return permission.description;
  }
  const translated = PERMISSION_DESCRIPTIONS[lang]?.[permission.code];
  return translated || permission.description || permission.code;
}
