/**
 * Screen copy for H1 (users administration) together with H3 (personal
 * grants) and H4 (sessions), local to this folder — the shared `src/i18n/`
 * dictionaries are owned by the shell and edited by every parallel track at
 * once, so a screen built in its own worktree carries its own strings.
 *
 * All languages are typed against `uz_latn`'s key set, so a key added to one and
 * forgotten in another is a compile error rather than a fallback string
 * appearing mid-sentence in the UI.
 */

export const uz_latn = {
  pageTitle: 'Foydalanuvchilar',
  pageSubtitle: 'Tizim xodimlari, ularning koʻrish zonasi va huquqlari',
  create: 'Yangi foydalanuvchi',

  // — counters
  statTotal: 'Jami foydalanuvchi',
  statActive: 'Faol',
  statBlocked: 'Bloklangan',
  statSessions: 'Faol seanslar',
  statsFailed: 'Hisoblagichlar yuklanmadi.',

  // — filters
  filterQuery: 'Qidiruv',
  filterQueryPlaceholder: 'Login, F.I.Sh. yoki JSHSHIR',
  filterQueryHint: 'Bitta maydon — login, F.I.Sh. va JSHSHIR boʻyicha qidiradi',
  filterRole: 'Rol',
  filterStatus: 'Holati',
  filterOrganization: 'Tashkilot',
  filterRegion: 'Hudud',
  filterAll: 'Barchasi',
  apply: 'Qoʻllash',
  reset: 'Tiklash',

  // — table
  colFullName: 'F.I.Sh.',
  colLogin: 'Login',
  colRole: 'Rol',
  colOrganization: 'Tashkilot',
  colStatus: 'Holati',
  colActions: 'Amallar',
  openCard: 'Karta',
  loading: 'Yuklanmoqda...',
  empty: 'Filtr boʻyicha foydalanuvchi topilmadi.',
  loadFailed: 'Foydalanuvchilar roʻyxati yuklanmadi.',
  noValue: '—',
  wholeRepublic: 'Butun respublika',

  // — statuses
  statusActive: 'Faol',
  statusBlocked: 'Bloklangan',
  statusDeleted: 'Oʻchirilgan',

  // — card
  cardTitle: 'Foydalanuvchi kartasi',
  cardLoading: 'Karta yuklanmoqda...',
  cardFailed: 'Foydalanuvchi maʼlumotlari yuklanmadi.',
  tabInfo: 'Maʼlumot',
  tabSessions: 'Seanslar',
  tabGrants: 'Shaxsiy huquqlar',
  close: 'Yopish',

  fieldLogin: 'Login',
  fieldFullName: 'F.I.Sh.',
  fieldPinfl: 'JSHSHIR',
  fieldPosition: 'Lavozimi',
  fieldRole: 'Rol',
  fieldOrganization: 'Tashkilot',
  fieldRegion: 'Hudud',
  fieldDistrict: 'Tuman',
  fieldPhone: 'Telefon',
  fieldEmail: 'Elektron pochta',
  fieldStatus: 'Holati',
  fieldCreatedAt: 'Yaratilgan',
  fieldLastLogin: 'Oxirgi kirish',
  mustChangePassword: 'Parolni almashtirishi shart',

  // — actions
  actionEdit: 'Tahrirlash',
  actionBlock: 'Bloklash',
  actionUnblock: 'Blokdan chiqarish',
  actionDelete: 'Oʻchirish',
  actionResetPassword: 'Parolni tiklash',
  actionResetMfa: 'MFA ni tiklash',
  actionsTitle: 'Amallar',

  // — create / edit form
  createTitle: 'Yangi foydalanuvchi',
  createSubtitle: 'Xodim hisobi. Fuqarolar bu yerda yaratilmaydi.',
  editTitle: 'Foydalanuvchini tahrirlash',
  editSubtitle: 'Faqat oʻzgartirilgan maydonlar yuboriladi.',
  formLogin: 'Login',
  formFullName: 'F.I.Sh.',
  formRole: 'Rol',
  formRoleHint: 'Fuqarolar (applicant) OneID yoki E-IMZO orqali roʻyxatdan oʻtadi — bu yerda yaratilmaydi.',
  formPinfl: 'JSHSHIR',
  formPinflHint: '14 ta raqam',
  formPosition: 'Lavozimi',
  formSelect: 'Tanlang',
  save: 'Saqlash',
  cancel: 'Bekor qilish',
  saving: 'Saqlanmoqda...',
  nothingChanged: 'Hech narsa oʻzgartirilmadi.',
  errRequired: 'Toʻldirilishi shart',
  errPinfl: 'JSHSHIR 14 ta raqamdan iborat boʻlishi kerak',
  saveFailed: 'Saqlab boʻlmadi.',

  // — zone
  zoneTitle: 'Koʻrish zonasi',
  zoneWarning:
    'Zona maydonlari foydalanuvchi NIMANI koʻrishini belgilaydi. Boʻsh qoldirish — betaraf holat emas: tashkilot koʻrsatilmasa, foydalanuvchi tanlangan hududdagi BARCHA oʻrmon xoʻjaliklarini koʻradi; uchala maydon ham boʻsh boʻlsa — butun respublika maʼlumotlarini koʻradi.',
  zoneOrganization: 'Tashkilot',
  zoneRegion: 'Hudud',
  zoneDistrict: 'Tuman',
  zoneDistrictHint: 'Avval hudud tanlanadi — tumanlar shu hudud boʻyicha filtrlanadi.',
  zoneDistrictDisabled: 'Avval hududni tanlang',

  // — block dialog
  blockTitle: 'Foydalanuvchini bloklash',
  blockReason: 'Sabab',
  blockReasonHint: 'Sabab audit jurnaliga yoziladi va oʻchirilmaydi.',
  blockReasonRequired: 'Bloklash sababini koʻrsating — usiz amal bajarilmaydi.',
  blockConfirm: 'Bloklash',
  blockFailed: 'Bloklab boʻlmadi.',

  // — confirmations
  confirmUnblockTitle: 'Blokdan chiqarilsinmi?',
  confirmUnblockBody: 'Foydalanuvchi tizimga qayta kira oladi.',
  confirmDeleteTitle: 'Foydalanuvchi oʻchirilsinmi?',
  confirmDeleteBody:
    'Yozuv saqlanadi, holati «Oʻchirilgan» boʻladi va foydalanuvchi tizimga kira olmaydi.',
  confirmResetPasswordTitle: 'Parol tiklansinmi?',
  confirmResetPasswordBody:
    'Yangi bir martalik parol yaratiladi va faqat bir marta koʻrsatiladi. Eski parol darhol ishlamay qoladi.',
  confirmResetMfaTitle: 'MFA tiklansinmi?',
  confirmResetMfaBody:
    'Yangi TOTP havolasi yaratiladi va faqat bir marta koʻrsatiladi. Eski autentifikator ishlamay qoladi.',
  confirm: 'Tasdiqlash',
  actionFailed: 'Amalni bajarib boʻlmadi.',

  // — one-time secret
  secretTitle: 'Bu maʼlumot faqat BIR MARTA koʻrsatiladi',
  secretIntro:
    'Server bu qiymatlarni boshqa hech qachon koʻrsatmaydi. Hozir nusxa oling va foydalanuvchiga xavfsiz yoʻl bilan yetkazing. Yoʻqotilsa — yagona chora qayta tiklash.',
  secretPassword: 'Bir martalik parol',
  secretPasswordHint: 'Foydalanuvchi birinchi kirishda uni almashtirishi shart.',
  secretTotp: 'TOTP havolasi (autentifikator uchun)',
  secretTotpHint:
    'Havolani autentifikator ilovasiga qoʻlda kiriting yoki nusxalab yuboring — QR kod bu yerda chizilmaydi.',
  copy: 'Nusxalash',
  copied: 'Nusxalandi',
  copyFailed: 'Nusxalab boʻlmadi — matnni qoʻlda belgilang.',
  secretAck: 'Saqlab oldim',
  secretAckHint: 'Panel faqat shu tugma bosilganda yopiladi.',

  // — sessions (H4)
  sessionsTitle: 'Faol seanslar',
  sessionsHint: 'Har bir qator — bitta qurilmadagi ochiq seans.',
  sessionCreated: 'Boshlangan',
  sessionLastSeen: 'Oxirgi faollik',
  sessionExpires: 'Amal qilish muddati',
  sessionIp: 'IP',
  sessionDevice: 'Qurilma',
  sessionRevoke: 'Tugatish',
  sessionRevokeAll: 'Barcha seanslarni tugatish',
  sessionsEmpty: 'Ochiq seans yoʻq.',
  sessionsFailed: 'Seanslar yuklanmadi.',
  sessionsRevoked: 'Seans tugatildi.',
  sessionsRevokeFailed: 'Seansni tugatib boʻlmadi.',

  // — personal grants (H3)
  grantsTitle: 'Shaxsiy huquqlar',
  grantsNotice:
    'Bu roʻyxat — ROL huquqlariga QOʻSHIMCHA ravishda berilgan huquqlar. Bu foydalanuvchining toʻliq huquqlari emas: rol bergan huquqlar bu yerda belgilanmaydi va bu yerdan olib tashlanmaydi.',
  grantsRoleHint: 'Rol huquqlari «Rollar» ekranida boshqariladi.',
  grantsSave: 'Huquqlarni saqlash',
  grantsSaved: 'Shaxsiy huquqlar saqlandi.',
  grantsFailed: 'Huquqlar yuklanmadi.',
  grantsSaveFailed: 'Huquqlarni saqlab boʻlmadi.',
  grantsEmpty: 'Huquqlar roʻyxati boʻsh.',
  grantsSelected: 'Belgilangan',
} as const;

export type UsersLabels = Record<keyof typeof uz_latn, string>;

export const ru: UsersLabels = {
  pageTitle: 'Пользователи',
  pageSubtitle: 'Сотрудники системы, их зона видимости и права',
  create: 'Новый пользователь',

  statTotal: 'Всего пользователей',
  statActive: 'Активные',
  statBlocked: 'Заблокированные',
  statSessions: 'Активные сессии',
  statsFailed: 'Счётчики не загрузились.',

  filterQuery: 'Поиск',
  filterQueryPlaceholder: 'Логин, Ф.И.О. или ПИНФЛ',
  filterQueryHint: 'Одно поле — ищет по логину, Ф.И.О. и ПИНФЛ',
  filterRole: 'Роль',
  filterStatus: 'Статус',
  filterOrganization: 'Организация',
  filterRegion: 'Регион',
  filterAll: 'Все',
  apply: 'Применить',
  reset: 'Сбросить',

  colFullName: 'Ф.И.О.',
  colLogin: 'Логин',
  colRole: 'Роль',
  colOrganization: 'Организация',
  colStatus: 'Статус',
  colActions: 'Действия',
  openCard: 'Карточка',
  loading: 'Загрузка...',
  empty: 'По фильтру пользователи не найдены.',
  loadFailed: 'Список пользователей не загрузился.',
  noValue: '—',
  wholeRepublic: 'Вся республика',

  statusActive: 'Активен',
  statusBlocked: 'Заблокирован',
  statusDeleted: 'Удалён',

  cardTitle: 'Карточка пользователя',
  cardLoading: 'Карточка загружается...',
  cardFailed: 'Данные пользователя не загрузились.',
  tabInfo: 'Данные',
  tabSessions: 'Сессии',
  tabGrants: 'Личные права',
  close: 'Закрыть',

  fieldLogin: 'Логин',
  fieldFullName: 'Ф.И.О.',
  fieldPinfl: 'ПИНФЛ',
  fieldPosition: 'Должность',
  fieldRole: 'Роль',
  fieldOrganization: 'Организация',
  fieldRegion: 'Регион',
  fieldDistrict: 'Район',
  fieldPhone: 'Телефон',
  fieldEmail: 'Электронная почта',
  fieldStatus: 'Статус',
  fieldCreatedAt: 'Создан',
  fieldLastLogin: 'Последний вход',
  mustChangePassword: 'Обязан сменить пароль',

  actionEdit: 'Редактировать',
  actionBlock: 'Заблокировать',
  actionUnblock: 'Разблокировать',
  actionDelete: 'Удалить',
  actionResetPassword: 'Сбросить пароль',
  actionResetMfa: 'Сбросить MFA',
  actionsTitle: 'Действия',

  createTitle: 'Новый пользователь',
  createSubtitle: 'Учётная запись сотрудника. Граждане здесь не создаются.',
  editTitle: 'Редактирование пользователя',
  editSubtitle: 'Отправляются только изменённые поля.',
  formLogin: 'Логин',
  formFullName: 'Ф.И.О.',
  formRole: 'Роль',
  formRoleHint:
    'Граждане (applicant) регистрируются через OneID или E-IMZO — здесь они не создаются.',
  formPinfl: 'ПИНФЛ',
  formPinflHint: '14 цифр',
  formPosition: 'Должность',
  formSelect: 'Выберите',
  save: 'Сохранить',
  cancel: 'Отмена',
  saving: 'Сохранение...',
  nothingChanged: 'Ничего не изменено.',
  errRequired: 'Обязательное поле',
  errPinfl: 'ПИНФЛ состоит из 14 цифр',
  saveFailed: 'Не удалось сохранить.',

  zoneTitle: 'Зона видимости',
  zoneWarning:
    'Поля зоны определяют, ЧТО пользователь видит. Пустое значение — не нейтральный вариант: без организации пользователь видит ВСЕ лесхозы выбранного региона, а если пусты все три поля — данные всей республики.',
  zoneOrganization: 'Организация',
  zoneRegion: 'Регион',
  zoneDistrict: 'Район',
  zoneDistrictHint: 'Сначала выбирается регион — районы фильтруются по нему.',
  zoneDistrictDisabled: 'Сначала выберите регион',

  blockTitle: 'Блокировка пользователя',
  blockReason: 'Причина',
  blockReasonHint: 'Причина попадает в журнал аудита и не удаляется.',
  blockReasonRequired: 'Укажите причину блокировки — без неё действие не выполняется.',
  blockConfirm: 'Заблокировать',
  blockFailed: 'Не удалось заблокировать.',

  confirmUnblockTitle: 'Разблокировать?',
  confirmUnblockBody: 'Пользователь снова сможет войти в систему.',
  confirmDeleteTitle: 'Удалить пользователя?',
  confirmDeleteBody:
    'Запись сохраняется, статус становится «Удалён», вход в систему закрывается.',
  confirmResetPasswordTitle: 'Сбросить пароль?',
  confirmResetPasswordBody:
    'Будет создан новый одноразовый пароль и показан только один раз. Старый пароль перестанет работать сразу.',
  confirmResetMfaTitle: 'Сбросить MFA?',
  confirmResetMfaBody:
    'Будет создана новая TOTP-ссылка и показана только один раз. Старый аутентификатор перестанет работать.',
  confirm: 'Подтвердить',
  actionFailed: 'Не удалось выполнить действие.',

  secretTitle: 'Эти данные показываются ТОЛЬКО ОДИН РАЗ',
  secretIntro:
    'Сервер больше никогда их не покажет. Скопируйте сейчас и передайте пользователю безопасным способом. Если потеряете — останется только повторный сброс.',
  secretPassword: 'Одноразовый пароль',
  secretPasswordHint: 'При первом входе пользователь обязан его сменить.',
  secretTotp: 'TOTP-ссылка (для аутентификатора)',
  secretTotpHint:
    'Введите ссылку в приложение-аутентификатор вручную или скопируйте её — QR-код здесь не рисуется.',
  copy: 'Копировать',
  copied: 'Скопировано',
  copyFailed: 'Не удалось скопировать — выделите текст вручную.',
  secretAck: 'Я сохранил(а) эти данные',
  secretAckHint: 'Панель закрывается только по этой кнопке.',

  sessionsTitle: 'Активные сессии',
  sessionsHint: 'Каждая строка — открытая сессия на одном устройстве.',
  sessionCreated: 'Начата',
  sessionLastSeen: 'Последняя активность',
  sessionExpires: 'Действует до',
  sessionIp: 'IP',
  sessionDevice: 'Устройство',
  sessionRevoke: 'Завершить',
  sessionRevokeAll: 'Завершить все сессии',
  sessionsEmpty: 'Открытых сессий нет.',
  sessionsFailed: 'Сессии не загрузились.',
  sessionsRevoked: 'Сессия завершена.',
  sessionsRevokeFailed: 'Не удалось завершить сессию.',

  grantsTitle: 'Личные права',
  grantsNotice:
    'Этот список — права, выданные ДОПОЛНИТЕЛЬНО к правам РОЛИ. Это не полный набор прав пользователя: права от роли здесь не отмечаются и отсюда не снимаются.',
  grantsRoleHint: 'Права роли настраиваются на экране «Роли».',
  grantsSave: 'Сохранить права',
  grantsSaved: 'Личные права сохранены.',
  grantsFailed: 'Права не загрузились.',
  grantsSaveFailed: 'Не удалось сохранить права.',
  grantsEmpty: 'Список прав пуст.',
  grantsSelected: 'Отмечено',
};

export const uz_cyrl: UsersLabels = {
  pageTitle: 'Фойдаланувчилар',
  pageSubtitle: 'Тизим ходимлари, уларнинг кўриш зонаси ва ҳуқуқлари',
  create: 'Янги фойдаланувчи',

  statTotal: 'Жами фойдаланувчи',
  statActive: 'Фаол',
  statBlocked: 'Блокланган',
  statSessions: 'Фаол сеанслар',
  statsFailed: 'Ҳисоблагичлар юкланмади.',

  filterQuery: 'Қидирув',
  filterQueryPlaceholder: 'Логин, Ф.И.Ш. ёки ЖШШИР',
  filterQueryHint: 'Битта майдон — логин, Ф.И.Ш. ва ЖШШИР бўйича қидиради',
  filterRole: 'Рол',
  filterStatus: 'Ҳолати',
  filterOrganization: 'Ташкилот',
  filterRegion: 'Ҳудуд',
  filterAll: 'Барчаси',
  apply: 'Қўллаш',
  reset: 'Тиклаш',

  colFullName: 'Ф.И.Ш.',
  colLogin: 'Логин',
  colRole: 'Рол',
  colOrganization: 'Ташкилот',
  colStatus: 'Ҳолати',
  colActions: 'Амаллар',
  openCard: 'Карта',
  loading: 'Юкланмоқда...',
  empty: 'Фильтр бўйича фойдаланувчи топилмади.',
  loadFailed: 'Фойдаланувчилар рўйхати юкланмади.',
  noValue: '—',
  wholeRepublic: 'Бутун республика',

  statusActive: 'Фаол',
  statusBlocked: 'Блокланган',
  statusDeleted: 'Ўчирилган',

  cardTitle: 'Фойдаланувчи картаси',
  cardLoading: 'Карта юкланмоқда...',
  cardFailed: 'Фойдаланувчи маълумотлари юкланмади.',
  tabInfo: 'Маълумот',
  tabSessions: 'Сеанслар',
  tabGrants: 'Шахсий ҳуқуқлар',
  close: 'Ёпиш',

  fieldLogin: 'Логин',
  fieldFullName: 'Ф.И.Ш.',
  fieldPinfl: 'ЖШШИР',
  fieldPosition: 'Лавозими',
  fieldRole: 'Рол',
  fieldOrganization: 'Ташкилот',
  fieldRegion: 'Ҳудуд',
  fieldDistrict: 'Туман',
  fieldPhone: 'Телефон',
  fieldEmail: 'Электрон почта',
  fieldStatus: 'Ҳолати',
  fieldCreatedAt: 'Яратилган',
  fieldLastLogin: 'Охирги кириш',
  mustChangePassword: 'Паролни алмаштириши шарт',

  actionEdit: 'Таҳрирлаш',
  actionBlock: 'Блоклаш',
  actionUnblock: 'Блокдан чиқариш',
  actionDelete: 'Ўчириш',
  actionResetPassword: 'Паролни тиклаш',
  actionResetMfa: 'MFA ни тиклаш',
  actionsTitle: 'Амаллар',

  createTitle: 'Янги фойдаланувчи',
  createSubtitle: 'Ходим ҳисоби. Фуқаролар бу ерда яратилмайди.',
  editTitle: 'Фойдаланувчини таҳрирлаш',
  editSubtitle: 'Фақат ўзгартирилган майдонлар юборилади.',
  formLogin: 'Логин',
  formFullName: 'Ф.И.Ш.',
  formRole: 'Рол',
  formRoleHint:
    'Фуқаролар (applicant) OneID ёки E-IMZO орқали рўйхатдан ўтади — бу ерда яратилмайди.',
  formPinfl: 'ЖШШИР',
  formPinflHint: '14 та рақам',
  formPosition: 'Лавозими',
  formSelect: 'Танланг',
  save: 'Сақлаш',
  cancel: 'Бекор қилиш',
  saving: 'Сақланмоқда...',
  nothingChanged: 'Ҳеч нарса ўзгартирилмади.',
  errRequired: 'Тўлдирилиши шарт',
  errPinfl: 'ЖШШИР 14 та рақамдан иборат бўлиши керак',
  saveFailed: 'Сақлаб бўлмади.',

  zoneTitle: 'Кўриш зонаси',
  zoneWarning:
    'Зона майдонлари фойдаланувчи НИМАНИ кўришини белгилайди. Бўш қолдириш — бетараф ҳолат эмас: ташкилот кўрсатилмаса, фойдаланувчи танланган ҳудуддаги БАРЧА ўрмон хўжаликларини кўради; учала майдон ҳам бўш бўлса — бутун республика маълумотларини кўради.',
  zoneOrganization: 'Ташкилот',
  zoneRegion: 'Ҳудуд',
  zoneDistrict: 'Туман',
  zoneDistrictHint: 'Аввал ҳудуд танланади — туманлар шу ҳудуд бўйича фильтрланади.',
  zoneDistrictDisabled: 'Аввал ҳудудни танланг',

  blockTitle: 'Фойдаланувчини блоклаш',
  blockReason: 'Сабаб',
  blockReasonHint: 'Сабаб аудит журналига ёзилади ва ўчирилмайди.',
  blockReasonRequired: 'Блоклаш сабабини кўрсатинг — усиз амал бажарилмайди.',
  blockConfirm: 'Блоклаш',
  blockFailed: 'Блоклаб бўлмади.',

  confirmUnblockTitle: 'Блокдан чиқарилсинми?',
  confirmUnblockBody: 'Фойдаланувчи тизимга қайта кира олади.',
  confirmDeleteTitle: 'Фойдаланувчи ўчирилсинми?',
  confirmDeleteBody:
    'Ёзув сақланади, ҳолати «Ўчирилган» бўлади ва фойдаланувчи тизимга кира олмайди.',
  confirmResetPasswordTitle: 'Парол тиклансинми?',
  confirmResetPasswordBody:
    'Янги бир марталик парол яратилади ва фақат бир марта кўрсатилади. Эски парол дарҳол ишламай қолади.',
  confirmResetMfaTitle: 'MFA тиклансинми?',
  confirmResetMfaBody:
    'Янги TOTP ҳаволаси яратилади ва фақат бир марта кўрсатилади. Эски аутентификатор ишламай қолади.',
  confirm: 'Тасдиқлаш',
  actionFailed: 'Амални бажариб бўлмади.',

  secretTitle: 'Бу маълумот фақат БИР МАРТА кўрсатилади',
  secretIntro:
    'Сервер бу қийматларни бошқа ҳеч қачон кўрсатмайди. Ҳозир нусха олинг ва фойдаланувчига хавфсиз йўл билан етказинг. Йўқотилса — ягона чора қайта тиклаш.',
  secretPassword: 'Бир марталик парол',
  secretPasswordHint: 'Фойдаланувчи биринчи киришда уни алмаштириши шарт.',
  secretTotp: 'TOTP ҳаволаси (аутентификатор учун)',
  secretTotpHint:
    'Ҳаволани аутентификатор иловасига қўлда киритинг ёки нусхалаб юборинг — QR код бу ерда чизилмайди.',
  copy: 'Нусхалаш',
  copied: 'Нусхаланди',
  copyFailed: 'Нусхалаб бўлмади — матнни қўлда белгиланг.',
  secretAck: 'Сақлаб олдим',
  secretAckHint: 'Панел фақат шу тугма босилганда ёпилади.',

  sessionsTitle: 'Фаол сеанслар',
  sessionsHint: 'Ҳар бир қатор — битта қурилмадаги очиқ сеанс.',
  sessionCreated: 'Бошланган',
  sessionLastSeen: 'Охирги фаоллик',
  sessionExpires: 'Амал қилиш муддати',
  sessionIp: 'IP',
  sessionDevice: 'Қурилма',
  sessionRevoke: 'Тугатиш',
  sessionRevokeAll: 'Барча сеансларни тугатиш',
  sessionsEmpty: 'Очиқ сеанс йўқ.',
  sessionsFailed: 'Сеанслар юкланмади.',
  sessionsRevoked: 'Сеанс тугатилди.',
  sessionsRevokeFailed: 'Сеансни тугатиб бўлмади.',

  grantsTitle: 'Шахсий ҳуқуқлар',
  grantsNotice:
    'Бу рўйхат — РОЛ ҳуқуқларига ҚЎШИМЧА равишда берилган ҳуқуқлар. Бу фойдаланувчининг тўлиқ ҳуқуқлари эмас: рол берган ҳуқуқлар бу ерда белгиланмайди ва бу ердан олиб ташланмайди.',
  grantsRoleHint: 'Рол ҳуқуқлари «Роллар» экранида бошқарилади.',
  grantsSave: 'Ҳуқуқларни сақлаш',
  grantsSaved: 'Шахсий ҳуқуқлар сақланди.',
  grantsFailed: 'Ҳуқуқлар юкланмади.',
  grantsSaveFailed: 'Ҳуқуқларни сақлаб бўлмади.',
  grantsEmpty: 'Ҳуқуқлар рўйхати бўш.',
  grantsSelected: 'Белгиланган',
};

export const en: UsersLabels = {
  pageTitle: 'Users',
  pageSubtitle: 'System staff, their visibility zone and permissions',
  create: 'New user',

  statTotal: 'Total users',
  statActive: 'Active',
  statBlocked: 'Blocked',
  statSessions: 'Active sessions',
  statsFailed: 'Failed to load counters.',

  filterQuery: 'Search',
  filterQueryPlaceholder: 'Login, Full Name or PINFL',
  filterQueryHint: 'Single field — searches by login, full name and PINFL',
  filterRole: 'Role',
  filterStatus: 'Status',
  filterOrganization: 'Organization',
  filterRegion: 'Region',
  filterAll: 'All',
  apply: 'Apply',
  reset: 'Reset',

  colFullName: 'Full Name',
  colLogin: 'Login',
  colRole: 'Role',
  colOrganization: 'Organization',
  colStatus: 'Status',
  colActions: 'Actions',
  openCard: 'Card',
  loading: 'Loading...',
  empty: 'No users found matching the filter.',
  loadFailed: 'Failed to load user list.',
  noValue: '—',
  wholeRepublic: 'Entire republic',

  statusActive: 'Active',
  statusBlocked: 'Blocked',
  statusDeleted: 'Deleted',

  cardTitle: 'User Card',
  cardLoading: 'Loading card...',
  cardFailed: 'Failed to load user data.',
  tabInfo: 'Information',
  tabSessions: 'Sessions',
  tabGrants: 'Personal Permissions',
  close: 'Close',

  fieldLogin: 'Login',
  fieldFullName: 'Full Name',
  fieldPinfl: 'PINFL',
  fieldPosition: 'Position',
  fieldRole: 'Role',
  fieldOrganization: 'Organization',
  fieldRegion: 'Region',
  fieldDistrict: 'District',
  fieldPhone: 'Phone',
  fieldEmail: 'Email',
  fieldStatus: 'Status',
  fieldCreatedAt: 'Created',
  fieldLastLogin: 'Last login',
  mustChangePassword: 'Must change password',

  actionEdit: 'Edit',
  actionBlock: 'Block',
  actionUnblock: 'Unblock',
  actionDelete: 'Delete',
  actionResetPassword: 'Reset password',
  actionResetMfa: 'Reset MFA',
  actionsTitle: 'Actions',

  createTitle: 'New User',
  createSubtitle: 'Staff account. Citizens are not created here.',
  editTitle: 'Edit User',
  editSubtitle: 'Only modified fields will be sent.',
  formLogin: 'Login',
  formFullName: 'Full Name',
  formRole: 'Role',
  formRoleHint:
    'Citizens (applicant) register via OneID or E-IMZO — they are not created here.',
  formPinfl: 'PINFL',
  formPinflHint: '14 digits',
  formPosition: 'Position',
  formSelect: 'Select',
  save: 'Save',
  cancel: 'Cancel',
  saving: 'Saving...',
  nothingChanged: 'Nothing has changed.',
  errRequired: 'Required field',
  errPinfl: 'PINFL must be 14 digits',
  saveFailed: 'Failed to save.',

  zoneTitle: 'Visibility Zone',
  zoneWarning:
    'Zone fields determine WHAT the user sees. Leaving empty is not a neutral state: without an organization, the user sees ALL forestry enterprises in the selected region; if all three fields are empty — data of the entire republic.',
  zoneOrganization: 'Organization',
  zoneRegion: 'Region',
  zoneDistrict: 'District',
  zoneDistrictHint: 'Region is selected first — districts are filtered by it.',
  zoneDistrictDisabled: 'Select a region first',

  blockTitle: 'Block User',
  blockReason: 'Reason',
  blockReasonHint: 'The reason is recorded in the audit log and cannot be deleted.',
  blockReasonRequired: 'Specify a block reason — the action cannot be performed without it.',
  blockConfirm: 'Block',
  blockFailed: 'Failed to block user.',

  confirmUnblockTitle: 'Unblock user?',
  confirmUnblockBody: 'The user will be able to log in to the system again.',
  confirmDeleteTitle: 'Delete user?',
  confirmDeleteBody:
    'The record is preserved, the status becomes "Deleted", and system access is revoked.',
  confirmResetPasswordTitle: 'Reset password?',
  confirmResetPasswordBody:
    'A new one-time password will be generated and shown only once. The old password will stop working immediately.',
  confirmResetMfaTitle: 'Reset MFA?',
  confirmResetMfaBody:
    'A new TOTP link will be generated and shown only once. The old authenticator will stop working.',
  confirm: 'Confirm',
  actionFailed: 'Failed to perform action.',

  secretTitle: 'This information is shown ONLY ONCE',
  secretIntro:
    'The server will never show these values again. Copy them now and deliver them to the user securely. If lost, the only remedy is resetting again.',
  secretPassword: 'One-time password',
  secretPasswordHint: 'The user must change it on first login.',
  secretTotp: 'TOTP link (for authenticator)',
  secretTotpHint:
    'Enter the link into an authenticator app manually or copy it — a QR code is not generated here.',
  copy: 'Copy',
  copied: 'Copied',
  copyFailed: 'Failed to copy — select the text manually.',
  secretAck: 'I have saved this information',
  secretAckHint: 'The panel closes only when this button is clicked.',

  sessionsTitle: 'Active Sessions',
  sessionsHint: 'Each row represents an active session on a single device.',
  sessionCreated: 'Started',
  sessionLastSeen: 'Last active',
  sessionExpires: 'Expires at',
  sessionIp: 'IP',
  sessionDevice: 'Device',
  sessionRevoke: 'Terminate',
  sessionRevokeAll: 'Terminate all sessions',
  sessionsEmpty: 'No open sessions.',
  sessionsFailed: 'Failed to load sessions.',
  sessionsRevoked: 'Session terminated.',
  sessionsRevokeFailed: 'Failed to terminate session.',

  grantsTitle: 'Personal Permissions',
  grantsNotice:
    'This list contains permissions granted IN ADDITION to ROLE permissions. This is not the complete set of user permissions: role permissions are not checked here and cannot be revoked from here.',
  grantsRoleHint: 'Role permissions are managed on the "Roles" screen.',
  grantsSave: 'Save Permissions',
  grantsSaved: 'Personal permissions saved.',
  grantsFailed: 'Failed to load permissions.',
  grantsSaveFailed: 'Failed to save permissions.',
  grantsEmpty: 'Permission list is empty.',
  grantsSelected: 'Selected',
};

export const kaa: UsersLabels = {
  pageTitle: 'Paydalanıwshılar',
  pageSubtitle: 'Sistema xızmetkerleri, olardıń kóriw zonası hám huqıqları',
  create: 'Jańa paydalanıwshı',

  statTotal: 'Jámi paydalanıwshı',
  statActive: 'Aktiv',
  statBlocked: 'Bloklanǵan',
  statSessions: 'Aktiv seanslar',
  statsFailed: 'Esaplaǵıshlar júklenbedi.',

  filterQuery: 'İzlew',
  filterQueryPlaceholder: 'Login, F.I.SH. yamasa PINFL',
  filterQueryHint: 'Bir maydan — login, F.I.SH. hám PINFL boyınsha izleydi',
  filterRole: 'Rol',
  filterStatus: 'Jaǵdayı',
  filterOrganization: 'Shólkem',
  filterRegion: 'Wálayat',
  filterAll: 'Barlıǵı',
  apply: 'Qollaw',
  reset: 'Tiklew',

  colFullName: 'F.I.SH.',
  colLogin: 'Login',
  colRole: 'Rol',
  colOrganization: 'Shólkem',
  colStatus: 'Jaǵdayı',
  colActions: 'Ámeller',
  openCard: 'Karta',
  loading: 'Júklenbekte...',
  empty: 'Filtr boyınsha paydalanıwshı tabılmadı.',
  loadFailed: 'Paydalanıwshılar dizimi júklenbedi.',
  noValue: '—',
  wholeRepublic: 'Pútkil respublika',

  statusActive: 'Aktiv',
  statusBlocked: 'Bloklanǵan',
  statusDeleted: 'Óshirilgen',

  cardTitle: 'Paydalanıwshı kartası',
  cardLoading: 'Karta júklenbekte...',
  cardFailed: 'Paydalanıwshı maǵlıwmatları júklenbedi.',
  tabInfo: 'Maǵlıwmat',
  tabSessions: 'Seanslar',
  tabGrants: 'Jeke huqıqlar',
  close: 'Jabıw',

  fieldLogin: 'Login',
  fieldFullName: 'F.I.SH.',
  fieldPinfl: 'PINFL',
  fieldPosition: 'Lawazımı',
  fieldRole: 'Rol',
  fieldOrganization: 'Shólkem',
  fieldRegion: 'Wálayat',
  fieldDistrict: 'Rayon',
  fieldPhone: 'Telefon',
  fieldEmail: 'Elektron pochta',
  fieldStatus: 'Jaǵdayı',
  fieldCreatedAt: 'Jaratılǵan',
  fieldLastLogin: 'Aqırǵı kiriw',
  mustChangePassword: 'Paroldi almastırıwı shárt',

  actionEdit: 'Dúzetiw',
  actionBlock: 'Bloklaw',
  actionUnblock: 'Bloktan shıǵarıw',
  actionDelete: 'Óshiriw',
  actionResetPassword: 'Paroldi tiklew',
  actionResetMfa: 'MFA ni tiklew',
  actionsTitle: 'Ámeller',

  createTitle: 'Jańa paydalanıwshı',
  createSubtitle: 'Xızmetker esabı. Puqaralar bul jerde jaratılmaydı.',
  editTitle: 'Paydalanıwshını dúzetiw',
  editSubtitle: 'Tek ózgertilgen maydanlar jiberiledi.',
  formLogin: 'Login',
  formFullName: 'F.I.SH.',
  formRole: 'Rol',
  formRoleHint:
    'Puqaralar (applicant) OneID yamasa E-IMZO arqalı dizimnen ótedi — bul jerde jaratılmaydı.',
  formPinfl: 'PINFL',
  formPinflHint: '14 san',
  formPosition: 'Lawazımı',
  formSelect: 'Saylań',
  save: 'Saqlaw',
  cancel: 'Biykar etiw',
  saving: 'Saqlanbaqta...',
  nothingChanged: 'Hesh nárse ózgertilmedi.',
  errRequired: 'Toltırılıwı shárt',
  errPinfl: 'PINFL 14 sandan ibarat bolıwı kerek',
  saveFailed: 'Saqlap bolmadı.',

  zoneTitle: 'Kóriw zonası',
  zoneWarning:
    'Zona maydonları paydalanıwshı NENI kóretuǵının belgileydi. Bos qaldırıw — biytárep jaǵday emes: shólkem kórsetilmese, paydalanıwshı saylanǵan wálayattaǵı BARLIQ toǵay xojalıqların kóredi; úsh maydan da bos bolsa — pútkil respublika maǵlıwmatların kóredi.',
  zoneOrganization: 'Shólkem',
  zoneRegion: 'Wálayat',
  zoneDistrict: 'Rayon',
  zoneDistrictHint: 'Dáslep wálayat saylanadı — rayonlar sol wálayat boyınsha filtrlenedi.',
  zoneDistrictDisabled: 'Aldın wálayattı saylań',

  blockTitle: 'Paydalanıwshını bloklaw',
  blockReason: 'Sebep',
  blockReasonHint: 'Sebep audit jurnalına jazıladı hám óshirilmeydi.',
  blockReasonRequired: 'Bloklaw sebebin kórsetiń — usız ámel orınlanbaydı.',
  blockConfirm: 'Bloklaw',
  blockFailed: 'Bloklap bolmadı.',

  confirmUnblockTitle: 'Bloktan shıǵarılsınba?',
  confirmUnblockBody: 'Paydalanıwshı sistemaǵa qaytadan kire aladı.',
  confirmDeleteTitle: 'Paydalanıwshı óshirilsinbe?',
  confirmDeleteBody:
    'Jazba saqlanadı, jaǵdayı «Óshirilgen» boladı hám paydalanıwshı sistemaǵa kire almaydı.',
  confirmResetPasswordTitle: 'Parol tiklensinbe?',
  confirmResetPasswordBody:
    'Jańa bir martalıq parol jaratıladı hám tek bir márte kórsetiledi. Eski parol dárhal islemey qaladı.',
  confirmResetMfaTitle: 'MFA tiklensinbe?',
  confirmResetMfaBody:
    'Jańa TOTP siltemesi jaratıladı hám tek bir márte kórsetiledi. Eski autentifikator islemey qaladı.',
  confirm: 'Tastıyıqlaw',
  actionFailed: 'Ámeldi orınlap bolmadı.',

  secretTitle: 'Bul maǵlıwmat tek BIR MÁRTE kórsetiledi',
  secretIntro:
    'Server bul mánislerdi basqa hesh qashan kórsetpeydi. Házir kóshirip alıń hám paydalanıwshıǵa qáwipsiz jol menen jetkiziń. Joǵaltılsa — jalǵız shara qaytadan tiklew.',
  secretPassword: 'Bir martalıq parol',
  secretPasswordHint: 'Paydalanıwshı birinshi kiriwde onı almastırıwı shárt.',
  secretTotp: 'TOTP siltemesi (autentifikator ushın)',
  secretTotpHint:
    'Siltemeni autentifikator qosımshasına qol menen kiritiń yamasa kóshirip jiberiń — QR-kod bul jerde sızılmaydı.',
  copy: 'Kóshirip alıw',
  copied: 'Kóshirip alındı',
  copyFailed: 'Kóshirip alıp bolmadı — tekstti qol menen belgileń.',
  secretAck: 'Saqlap aldım',
  secretAckHint: 'Panel tek usı túyme basılǵanda jabıladı.',

  sessionsTitle: 'Aktiv seanslar',
  sessionsHint: 'Hár bir qatar — bir qurılmadaǵı ashıq seans.',
  sessionCreated: 'Baslanǵan',
  sessionLastSeen: 'Aqırǵı belsendilik',
  sessionExpires: 'Ámel etiw múddeti',
  sessionIp: 'IP',
  sessionDevice: 'Qurılma',
  sessionRevoke: 'Juwmaqlaw',
  sessionRevokeAll: 'Barlıq seanslardı juwmaqlaw',
  sessionsEmpty: 'Ashıq seans joq.',
  sessionsFailed: 'Seanslar júklenbedi.',
  sessionsRevoked: 'Seans juwmaqlandı.',
  sessionsRevokeFailed: 'Seanstı juwmaqlap bolmadı.',

  grantsTitle: 'Jeke huqıqlar',
  grantsNotice:
    'Bul dizim — ROL huqıqlarına QOSÍMCHA túrde berilgen huqıqlar. Bul paydalanıwshınıń tolıq huqıqları emes: rol bergen huqıqlar bul jerde belgilenbeydi hám bul jerden alıp taslanbaydı.',
  grantsRoleHint: 'Rol huqıqları «Roller» ekranında basqarıladı.',
  grantsSave: 'Huqıqlardı saqlaw',
  grantsSaved: 'Jeke huqıqlar saqlandı.',
  grantsFailed: 'Huqıqlar júklenbedi.',
  grantsSaveFailed: 'Huqıqlardı saqlap bolmadı.',
  grantsEmpty: 'Huqıqlar dizimi bos.',
  grantsSelected: 'Belgilengen',
};

import type { UiLanguage } from '../../../i18n/context';

export const LABELS: Record<UiLanguage, UsersLabels> = {
  uz_latn,
  uz_cyrl,
  ru,
  en,
  kaa,
};

export function labelsFor(lang: UiLanguage | string): UsersLabels {
  return (LABELS as Record<string, UsersLabels>)[lang] ?? uz_latn;
}
